### PR TITLE
New Frontpage

### PR DESCRIPTION
**Pull request by danchen**
DON'T MERGE YET

---
Steps to run:
```
git remote add git@github.com:danchen/elide-doc.git
git checkout danchen/new_frontpage

brew install cmake
gem install bundler minima jekyll-feed jekyll gh-pages

bundle exec jekyll s
```

---
Screenshot:
screenshot-localhost-4000-2017-11-30-15-36-28-689

### CODE REVIEW

**Comment by DennisMcWherter** [comment]
To run, requires you need to `gem install` a few deps:

```
bundler
minima
jekyll-feed
```

Maybe we should add these deps to the README?

**Comment by DennisMcWherter** [comment]
Tagline update, maybe something along the lines:

```
 Quickly build and deploy secure web API's in 4 easy steps.
```

**Comment by clayreimann** [comment]
This does not work on Sierra. I can't `gem install gh-pages` with the stock ruby, will try with brew installed ruby

Edit: I was actually missing `cmake`, that needs doc'ing.

**Comment by danchen** [comment]
Pulled in with https://github.com/yahoo/elide-doc/pull/52

**Pull request closed without merging**
